name: Economy
version: ${project.version}
author: Nathan Fiscaletti
api-version: 1.18
main: prison.nf.economy.EconomyPlugin

depend:
  - Storage

commands:
  eco:
    description: Commands related to server economy